# Generated by Django 4.0.1 on 2022-01-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_produtos_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
